package jlox;

enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, FORTH_SLASH, BACK_SLASH, STAR, QUOTATION, DOUBLE_QUOTATION,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
 
    // Literals.
    IDENTIFIER, STRING, NUMBER,
 
    // Keywords.
    AND, CLASS, OTHERWISE, FALSE, FUN, FOR, IF, NIL, OR, XOR,
    PRINT, RETURN, PARENT, THIS, TRUE, DEF, LOOP,
    EOF
}
